// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/tool/crypt": {
            "post": {
                "description": "使用bcrypt加密串，返回hash值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "获取Crypt Hash",
                "parameters": [
                    {
                        "description": "要Hash的串",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modules.CryptBindingModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Hash值",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "需要提供要Hash的串",
                        "schema": {
                            "$ref": "#/definitions/modules.ErrorViewModel"
                        }
                    }
                }
            }
        },
        "/api/v1/tool/uuid": {
            "get": {
                "description": "获取10个UUID，返回UUID列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "获取UUID",
                "responses": {
                    "200": {
                        "description": "UUID列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tool/viewObjectId": {
            "post": {
                "description": "查看ObjectId信息，包括时间戳、MAC、PID和Counter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tool"
                ],
                "summary": "查看ObjectId信息",
                "parameters": [
                    {
                        "description": "要查看的ObjectId",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/modules.ViewObjectIdBindingModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ObjectId信息",
                        "schema": {
                            "$ref": "#/definitions/modules.ViewObjectIdViewModel"
                        }
                    },
                    "400": {
                        "description": "需要提供有效的ObjectId",
                        "schema": {
                            "$ref": "#/definitions/modules.ErrorViewModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "modules.CryptBindingModel": {
            "type": "object",
            "required": [
                "str"
            ],
            "properties": {
                "str": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "modules.ErrorViewModel": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error message"
                }
            }
        },
        "modules.ViewObjectIdBindingModel": {
            "type": "object",
            "required": [
                "objectId"
            ],
            "properties": {
                "objectId": {
                    "type": "string",
                    "example": "5ffd59f403762e429ea59a72"
                }
            }
        },
        "modules.ViewObjectIdViewModel": {
            "type": "object",
            "properties": {
                "counter": {
                    "type": "integer"
                },
                "machine": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pid": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
